# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
