# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showsearch', '0002_auto_20180716_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
