# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsearch', '0003_auto_20180716_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
