# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsearch', '0004_auto_20180716_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='votes',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='season',
            name='number_of_episodes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='number_of_seasons',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='votes',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='season',
            name='rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='rating',
            field=models.FloatField(default=None),
        ),
    ]
