# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsearch', '0006_auto_20180718_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
