# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsearch', '0007_auto_20180718_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
