# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsearch', '0008_auto_20180719_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='votes',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='number_of_episodes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='number_of_seasons',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='votes',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
